// ReportCard.jsx

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
    formatDate,
    formatType,
} from '../utils/reportHelpers.js';
import ReportActionButtons from './ReportActionButtons.jsx';
import ReportHoverPreview from './ReportHoverPreview.jsx';

const ReportCard = ({
    report,
    onFinalize,
    onEdit,
    onArchive,
    onRestore,
    onPermanentDelete,
    onDownload,
}) => {
    const navigate = useNavigate();
    const [showPreview, setShowPreview] = useState(false);

    // ── Status badge colors ────────────────────
    const statusBadge = {
        active:
            'bg-green-50 text-green-700 border border-green-200 dark:bg-green-900/30 dark:text-green-400 dark:border-green-700',
        archived:
            'bg-slate-100 text-slate-500 border border-slate-200 dark:bg-slate-700 dark:text-slate-300 dark:border-slate-600',
    };

    // ── Finalized vs Draft badge ───────────────
    const finalizedBadge = report.isFinalized
        ? 'bg-theme-pale text-theme-navy border border-blue-200 dark:bg-slate-700 dark:text-white dark:border-slate-600'
        : 'bg-sky-100 text-sky-600 border border-sky-300 dark:bg-sky-900/30 dark:text-sky-400 dark:border-sky-700';

    // ── Card surface style ─────────────────────
    const cardSurfaceClass = report.isFinalized
        ? 'border-l-theme-navy bg-gradient-to-r from-blue-50/60 via-white to-white dark:from-slate-800 dark:via-slate-800 dark:to-slate-800'
        : 'border-l-sky-300 bg-gradient-to-r from-sky-50/70 via-white to-white dark:from-slate-800 dark:via-slate-800 dark:to-slate-800';

    return (
        <div
            className={`rounded-2xl p-5 border border-slate-100 dark:border-slate-700 border-l-4 shadow-sm hover:shadow-md hover:-translate-y-[1px] transition-all duration-200 ${cardSurfaceClass}`}
        >
            {/* Top row */}
            <div className="flex flex-wrap items-start justify-between gap-3 mb-3">
                <div className="relative inline-block max-w-full">
                    <h3
                        className="text-base font-bold text-theme-navy dark:text-white cursor-pointer hover:underline break-words"
                        onClick={() => navigate(`/admin/reports/${report._id}`)}
                        onMouseEnter={() => setShowPreview(true)}
                        onMouseLeave={() => setShowPreview(false)}
                    >
                        {report.title || 'Untitled Report'}
                    </h3>

                    {showPreview && <ReportHoverPreview report={report} />}
                </div>

                <div className="flex gap-2 flex-wrap">
                    <span
                        className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                            statusBadge[report.status] ||
                            'bg-slate-100 text-slate-500 border border-slate-200 dark:bg-slate-700 dark:text-slate-300'
                        }`}
                    >
                        {report.status === 'active' ? 'Active' : 'Archived'}
                    </span>

                    <span
                        className={`text-xs px-2 py-0.5 rounded-full font-medium ${finalizedBadge}`}
                    >
                        {report.isFinalized ? 'Finalized' : 'Draft'}
                    </span>
                </div>
            </div>

            {/* Summary */}
            <p className="text-sm text-slate-600 dark:text-slate-400 mb-4 leading-relaxed">
                {formatType(report.type)} report • {formatDate(report.periodStart)} –{' '}
                {formatDate(report.periodEnd)} • {report.totalBooks ?? 0} books •{' '}
                {report.lostBooks ?? 0} lost
            </p>

            {/* Info grid */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-sm mb-4">
                <div>
                    <p className="text-slate-400 dark:text-slate-500 text-xs mb-1">
                        Generated By
                    </p>
                    <p className="text-sm font-medium text-slate-700 dark:text-slate-200">
                        {report.generatedBy?.fullName || '—'}
                    </p>
                </div>

                <div>
                    <p className="text-slate-400 dark:text-slate-500 text-xs mb-1">
                        Created
                    </p>
                    <p className="text-sm font-medium text-slate-700 dark:text-slate-200">
                        {formatDate(report.createdAt)}
                    </p>
                </div>

                <div>
                    <p className="text-slate-400 dark:text-slate-500 text-xs mb-1">
                        Last Updated
                    </p>
                    <p className="text-sm font-medium text-slate-700 dark:text-slate-200">
                        {formatDate(report.updatedAt)}
                    </p>
                </div>
            </div>

            {/* Actions */}
            <div className="border-t border-slate-100 dark:border-slate-700 pt-4">
                <ReportActionButtons
                    report={report}
                    onFinalize={onFinalize}
                    onEdit={onEdit}
                    onArchive={onArchive}
                    onRestore={onRestore}
                    onPermanentDelete={onPermanentDelete}
                    onDownload={onDownload}
                />
            </div>
        </div>
    );
};

export default ReportCard;