// ReportTable.jsx

import {
    formatDate,
    formatDateTime,
    formatType,
    getTypeBadgeClass,
} from '../utils/reportHelpers.js';

const ReportTable = ({ report }) => {
    const totalBooks = report?.totalBooks ?? 0;
    const lostBooks = report?.lostBooks ?? 0;
    const netBooks = totalBooks - lostBooks;

    // 🎯 Subtle dark fixes ONLY where needed
    const statusBadgeClass =
        report.status === 'active'
            ? 'bg-emerald-50 text-emerald-700 border border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-700'
            : 'bg-slate-100 text-slate-600 border border-slate-200 dark:bg-slate-700 dark:text-slate-300 dark:border-slate-600';

    const finalizedBadgeClass = report.isFinalized
        ? 'bg-theme-pale text-theme-navy border border-blue-200 dark:bg-slate-700 dark:text-white dark:border-slate-600'
        : 'bg-sky-100 text-sky-800 border border-sky-300 dark:bg-sky-900/30 dark:text-sky-400 dark:border-sky-700';

    const infoRows = [
        { label: 'Report Title', value: report.title || 'Untitled Report' },
        {
            label: 'Type',
            value: (
                <span
                    className={`inline-flex items-center text-xs px-2.5 py-1 rounded-full font-medium ${getTypeBadgeClass(report.type)}`}
                >
                    {formatType(report.type)}
                </span>
            ),
        },
        {
            label: 'Status',
            value: (
                <span className={`inline-flex items-center text-xs px-2.5 py-1 rounded-full font-medium ${statusBadgeClass}`}>
                    {report.status === 'active' ? 'Active' : 'Archived'}
                </span>
            ),
        },
        {
            label: 'Draft / Finalized',
            value: (
                <span className={`inline-flex items-center text-xs px-2.5 py-1 rounded-full font-medium ${finalizedBadgeClass}`}>
                    {report.isFinalized ? 'Finalized' : 'Draft'}
                </span>
            ),
        },
        { label: 'Period Start', value: formatDate(report.periodStart) },
        { label: 'Period End', value: formatDate(report.periodEnd) },
        { label: 'Generated By', value: report.generatedBy?.fullName || '—' },
        {
            label: 'Generated On',
            value: report.createdAt ? formatDateTime(report.createdAt) : '—',
        },
        {
            label: 'Finalized At',
            value: report.finalizedAt ? formatDateTime(report.finalizedAt) : '—',
        },
        {
            label: 'Archived At',
            value: report.archivedAt ? formatDateTime(report.archivedAt) : '—',
        },
    ];

    const statsRows = [
        { label: 'Total Books', value: totalBooks },
        { label: 'Net Books', value: netBooks },
        { label: 'Lost Books', value: lostBooks },
        { label: 'New Users', value: report.totalNewUsers ?? 0 },
    ];

    return (
        <div className="space-y-6">
            {/* Report Info Table */}
            <div>
                <h3 className="text-sm font-semibold text-theme-navy dark:text-white mb-3 uppercase tracking-wide">
                    Report Information
                </h3>

                <div className="bg-white dark:bg-slate-800 border border-slate-100 dark:border-slate-700 rounded-2xl overflow-hidden shadow-sm transition-colors">
                    <table className="w-full text-sm border-collapse">
                        <tbody>
                            {infoRows.map((row, i) => (
                                <tr
                                    key={row.label}
                                    className={
                                        i % 2 === 0
                                            ? 'bg-white dark:bg-slate-800'
                                            : 'bg-theme-pale/20 dark:bg-slate-700/40'
                                    }
                                >
                                    <td className="px-5 py-3.5 text-slate-500 dark:text-slate-400 font-medium w-1/3 align-top">
                                        {row.label}
                                    </td>

                                    <td className="px-5 py-3.5 text-slate-800 dark:text-slate-200 font-medium align-top break-words">
                                        {row.value}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Stats Cards */}
            <div>
                <h3 className="text-sm font-semibold text-theme-navy dark:text-white mb-3 uppercase tracking-wide">
                    Report Statistics
                </h3>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    {statsRows.map((stat) => (
                        <div
                            key={stat.label}
                            className="bg-theme-pale/30 dark:bg-slate-800 border border-blue-100 dark:border-slate-700 rounded-2xl px-5 py-5 text-center shadow-sm transition-colors"
                        >
                            <p className="text-3xl font-bold text-theme-navy dark:text-white leading-none">
                                {stat.value}
                            </p>

                            <p className="text-xs font-medium text-slate-500 dark:text-slate-400 mt-2 uppercase tracking-wide">
                                {stat.label}
                            </p>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default ReportTable;