// ReportTimeline.jsx
// Displays a vertical activity timeline for a report
// Uses existing schema fields: createdAt, updatedAt, finalizedAt, archivedAt

import { formatDateTime, timeAgo } from '../utils/reportHelpers.js';
import {
    DocumentPlusIcon,
    PencilSquareIcon,
    LockClosedIcon,
    ArchiveBoxIcon,
} from '@heroicons/react/24/outline';

const ReportTimeline = ({ report }) => {
    const events = [];

    // 1. Always show — report was created
    events.push({
        icon: <DocumentPlusIcon className="w-4 h-4" />,
        bgColor: 'bg-green-100 dark:bg-green-900/30',
        iconColor: 'text-green-600 dark:text-green-300',
        dotColor: 'bg-green-500 dark:bg-green-400',
        cardColor: 'bg-green-50 border-green-200 dark:bg-green-900/10 dark:border-green-800/40',
        title: 'Report Created',
        description: `Generated by ${report.generatedBy?.fullName || 'Admin'}`,
        timestamp: report.createdAt,
    });

    // 2. Show if report was edited
    const wasEdited =
        (report.updatedAt &&
            new Date(report.updatedAt).getTime() !==
                new Date(report.createdAt).getTime() &&
            !report.finalizedAt) ||
        (report.updatedAt &&
            report.finalizedAt &&
            new Date(report.updatedAt).getTime() !==
                new Date(report.finalizedAt).getTime() &&
            new Date(report.updatedAt).getTime() !==
                new Date(report.createdAt).getTime());

    if (wasEdited) {
        events.push({
            icon: <PencilSquareIcon className="w-4 h-4" />,
            bgColor: 'bg-blue-100 dark:bg-blue-900/30',
            iconColor: 'text-theme-blue dark:text-blue-300',
            dotColor: 'bg-theme-blue dark:bg-blue-400',
            cardColor: 'bg-blue-50 border-blue-200 dark:bg-blue-900/10 dark:border-blue-800/40',
            title: 'Report Updated',
            description: 'Title or period dates were modified',
            timestamp: report.updatedAt,
        });
    }

    // 3. Show if finalized
    if (report.finalizedAt) {
        events.push({
            icon: <LockClosedIcon className="w-4 h-4" />,
            bgColor: 'bg-theme-pale dark:bg-blue-900/30',
            iconColor: 'text-theme-navy dark:text-blue-200',
            dotColor: 'bg-theme-navy dark:bg-blue-300',
            cardColor: 'bg-theme-pale/50 border-blue-200 dark:bg-blue-900/10 dark:border-blue-800/40',
            title: 'Report Finalized',
            description: 'Report locked — no further edits allowed',
            timestamp: report.finalizedAt,
        });
    }

    // 4. Show if archived
    if (report.archivedAt) {
        events.push({
            icon: <ArchiveBoxIcon className="w-4 h-4" />,
            bgColor: 'bg-yellow-100 dark:bg-yellow-900/30',
            iconColor: 'text-yellow-600 dark:text-yellow-300',
            dotColor: 'bg-yellow-500 dark:bg-yellow-400',
            cardColor: 'bg-yellow-50 border-yellow-200 dark:bg-yellow-900/10 dark:border-yellow-800/40',
            title: 'Report Archived',
            description: 'Moved to archive',
            timestamp: report.archivedAt,
        });
    }

    // Sort by timestamp
    events.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));

    return (
        <div className="mb-6">
            <h3 className="text-sm font-semibold text-theme-navy dark:text-white mb-4 uppercase tracking-wide">
                Activity Timeline
            </h3>

            <div className="bg-white dark:bg-slate-800 border border-slate-100 dark:border-slate-700 rounded-2xl p-6 shadow-sm transition-colors">
                <div className="relative">
                    {/* Vertical connecting line */}
                    <div className="absolute left-4 top-2 bottom-2 w-0.5 bg-slate-100 dark:bg-slate-700" />

                    <div className="space-y-6">
                        {events.map((event, index) => (
                            <div key={index} className="relative flex items-start gap-4 pl-10">
                                {/* Dot on timeline */}
                                <div
                                    className={`absolute left-2.5 top-1.5 w-3 h-3 rounded-full border-2 border-white dark:border-slate-800 shadow-sm ${event.dotColor}`}
                                />

                                {/* Event card */}
                                <div
                                    className={`flex-1 border rounded-xl px-4 py-3 transition-colors ${event.cardColor}`}
                                >
                                    <div className="flex items-center justify-between gap-2 flex-wrap">
                                        {/* Icon + title */}
                                        <div className="flex items-center gap-2">
                                            {/* Icon circle */}
                                            <div
                                                className={`w-6 h-6 rounded-full flex items-center justify-center ${event.bgColor} ${event.iconColor}`}
                                            >
                                                {event.icon}
                                            </div>
                                            <p className="text-sm font-semibold text-slate-700 dark:text-slate-200">
                                                {event.title}
                                            </p>
                                        </div>

                                        {/* Timestamp */}
                                        <p
                                            className="text-xs text-slate-400 dark:text-slate-500 cursor-default"
                                            title={formatDateTime(event.timestamp)}
                                        >
                                            {timeAgo(event.timestamp)}
                                        </p>
                                    </div>

                                    {/* Description */}
                                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 pl-8">
                                        {event.description}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReportTimeline;